### PR TITLE
Create debian

### PR DESCRIPTION
**Pull request by Fr-Dae**

### CODE REVIEW

**Comment by jsbackus** [comment]
Hi @Daebis, sorry for taking so long to get back to you. Is the intent to create release files for Ubuntu 16.04?

**Comment by Fr-Dae** [comment]
year, please can you creat  the 16.04 (and maybe 16.10) depot paquage for have a updated PPA =)

**Comment by jsbackus** [comment]
Hi @Daebis, sorry for taking so long to address this. @mtdeguzis has updated the repository at [libregeek](http://packages.libregeek.org/). Please see [issue 84](https://github.com/AntiMicro/antimicro/issues/84) under the main repository for more info. Thanks!

**Comment by mdeguzis** [comment]
Libregeek houses Debian vanilla. And some Ubuntu. Lately I have been pushing everyone to the PPA only, if you are a Ubuntu user or equivalent.

**Comment by mdeguzis** [comment]
I meant more along the lines that for Ubuntu folks. Use the PPA. All elss. My private repo.

**Pull request closed without merging**
